version: '3.8'

services:
  bot:
    build: fin_analyse_bot
    depends_on:
      - database
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - USER_ID=${USER_ID}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
    restart: on-failure

  database:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d:rw

volumes:
  postgres_data:
  pgadmin: